import Head from 'next/head'
import styles from '../styles/Contato.module.css'
import Section from '../components/Section/Section'
import BannerSection from '../components/Section/BannerSectionTest'
import banner from '../public/contatoBanner.png'
import ContactForm from '../components/ContactForm/ContactForm'
import Image from 'next/image'

export default function Contato() {

    const fields = [
        {id:'name', name:'Nome', type:'text', value:''},
        {id:'email', name:'E-mail', type:'email', value:''},
        {id:'message', name:'Mensagem', type:'text', value:''},
        {id:'curriculum', name:'Currículo', type:'file', value:''}
    ]

    return (
        <>
            <Head>
                <title>Contato - Clean Air</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main>

                <BannerSection img={banner} height="50vh"/>

                <Section id="contato" className={styles.contatoSection}>

                    <div className={styles.infos}>
                        <div className={styles.section}>
                            <div className={styles.title}>Atendimento</div>
                            <div className={styles.content}>
                                <p>De segunda à sexta</p>
                                <p>Das 08h às 17h50</p>
                            </div>
                        </div>
                        <div className={styles.section}>
                            <div className={styles.title}>Telefone</div>
                            <div className={styles.content}><p>(51) 3554.0017</p></div>
                        </div>
                        <div className={styles.section}>
                            <div className={styles.title}>Endereço</div>
                            <div className={styles.content}>
                                <p>Rua Ida Schuch, 46</p>
                                <p>Bairro Vicentina</p>
                                <p>São Leopoldo/RS</p>
                                <p>CEP: 93025-420</p>
                            </div>
                        </div>
                    </div>
                    <div className={styles.form}>
                        <div className={styles.title}>
                            Trabalhe conosco
                        </div>
                        <p>Queremos conhecer o seu talento, venha fazer parte da nossa equipe.</p>

                        <ContactForm
                            fields={fields}
                            apiBody={(state)=>{
                                    return {  
                                        action: 'signin',
                                        email: findValueById(state, 'email'), 
                                        password: findValueById(state, 'senha'),
                                    }
                                }
                            }
                            errorMessage="Houve um erro na tentativa de de fazer seu login. Recarregue a página e tente novamente."
                            successMessage="Login feito com sucesso!"
                            onSuccess={(response)=>{
                                setUser(response.user)
                                if( 'onSuccess' in props ){
                                    props.onSuccess()
                                }
                            }}

                            footerLeftEl=""
                            buttonText="Enviar"
                        />
                    </div>

                </Section>

            </main>            
            
        </>
    )
}
