import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Section from '../components/Section/Section'
import sectionStyles from '../components/Section/styles/Section.module.css'
import Bubble from '../components/Bubble/Bubble'
import BubbleContent from '../lib/bubbles.json'
import PortfolioSection from '../components/Cta/portfolio'
import NewsletterSection from '../components/Cta/newsletter'
import Footer from '../components/Footer/Footer'

export default function Home() {

    return (
        <>
            <Head>
                <title>Clean Air</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main>

                <Section id="bubbles" className={`${sectionStyles.grid} ${sectionStyles.col4} ${sectionStyles.gap4}`}>
                    {BubbleContent.map(item=>{
                        const img = <Image src={`/bubbles/${item.icon}.png`} layout="fill" objectFit="contain" alt={item.title} />
                        return <Bubble key={item.icon} title={item.title} icon={img}>{item.text}</Bubble>
                    })}
                </Section>

                <PortfolioSection/>

                <NewsletterSection/>

            </main>

            <Footer/>
            
        </>
    )
}
