import Head from 'next/head'
import Image from 'next/image'
import Section from '../components/Section/Section'
import sectionStyles from '../components/Section/styles/Section.module.css'
import BannerSection from '../components/Section/BannerSection'
import Bubble from '../components/Bubble/Bubble'
import BubbleContent from '../lib/bubbles.json'
import svgProjetos from '../public/bubbles/projetos.svg'
import svgManutencao from '../public/bubbles/manutencao.svg'
import svgInstalacao from '../public/bubbles/instalacao.svg'
import svgVendas from '../public/bubbles/vendas.svg'
import PortfolioSection from '../components/Cta/portfolio'
import Form from '../components/NewsForm'
import {findValueById} from '../lib/helper'

export default function Home() {

    const bubbleIcons = {
        'projetos': svgProjetos,
        'manutencao': svgManutencao,
        'instalacao': svgInstalacao,
        'vendas': svgVendas
    }

    const fields = [
        {id:'email', name:'E-mail', type:'email', value:''},
    ]

    return (
        <>
            <Head>
                <title>Clean Air</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main>

                <BannerSection/>

                <Section id="bubbles" className={`${sectionStyles.grid} ${sectionStyles.col4} ${sectionStyles.gap4}`}>
                    {BubbleContent.map(item=>{
                        const img = <Image src={bubbleIcons[item.icon]} layout="fill" objectFit="contain" alt={item.title} />
                        return <Bubble key={item.icon} title={item.title} icon={img}>{item.text}</Bubble>
                    })}
                </Section>

                <PortfolioSection/>

                <div className="container py-5 my-4">
                    <div className="row">
                        <div className="col-lg-6 col-sm-12">
                            <div className="w-100 h-100">
                                <img src="/newsletter.png" alt="ar condicionado central midea"/>
                            </div>
                        </div>
                        <div className="col-lg-6 col-sm-12 text-center">
                            <h3>Não perca nossas atualizações</h3>
                            <div className="mb-3">Preencha o campo abaixo e receba novidades por e-mail.</div>
                            <Form
                                fields={fields}
                                apiBody={(state)=>{
                                        return {  
                                            email: findValueById(state, 'email')
                                        }
                                    }
                                }
                                errorMessage="Houve um erro na tentativa de enviar seu email. Recarregue a página e tente novamente."
                                successMessage="Email enviado com sucesso!"
                                onSuccess={(response)=>{
                                    console.log("sucesso", response)
                                }}
    
                                footerLeftEl={null}
                                buttonText="Enviar"
                            />
                        </div>
                    </div>
                </div>

            </main>            
            
        </>
    )
}
